let remaining = parseInt(localStorage.getItem('remaining') || '3');
let usageHistory = JSON.parse(localStorage.getItem('usageHistory') || '[]');
document.addEventListener('DOMContentLoaded', () => { initGreeting(); initDate(); initWeather(); initNews(); initAI(); updateRemaining(); });
function initGreeting() { const hour = new Date().getHours(); let greeting = '你好'; if (hour < 12) greeting = '早上好'; else if (hour < 18) greeting = '下午好'; else greeting = '晚上好'; document.getElementById('greeting').textContent = greeting; }
function initDate() { const now = new Date(); const options = { weekday: 'long', month: 'long', day: 'numeric' }; document.getElementById('date').textContent = now.toLocaleDateString('zh-CN', options); }
async function initWeather() { try { const response = await fetch('https://wttr.in/Beijing?format=3'); const text = await response.text(); document.getElementById('weather').textContent = text; } catch (e) { document.getElementById('weather').textContent = '天气加载失败'; } }
async function initNews() { try { const response = await fetch('https://hacker-news.firebaseio.com/v0/topstories.json'); const ids = await response.json(); const top10 = ids.slice(0, 10); const newsList = document.getElementById('newsList'); newsList.innerHTML = ''; for (const id of top10) { const itemResponse = await fetch(`https://hacker-news.firebaseio.com/v0/item/${id}.json`); const item = await itemResponse.json(); const div = document.createElement('div'); div.className = 'news-item'; div.textContent = item.title; div.onclick = () => window.open(item.url, '_blank'); newsList.appendChild(div); } } catch (e) { document.getElementById('newsList').innerHTML = '<div class="news-item">热闻加载失败</div>'; } }
function initAI() { const input = document.getElementById('aiInput'); const btn = document.getElementById('askBtn'); input.addEventListener('keypress', (e) => { if (e.key === 'Enter') askAI(); }); btn.addEventListener('click', askAI); }
async function askAI() { const input = document.getElementById('aiInput'); const question = input.value.trim(); if (!question) return; if (remaining <= 0) { alert('今日免费次数已用完，请升级Pro继续使用！'); return; } const responseDiv = document.getElementById('aiResponse'); const contentDiv = document.getElementById('responseContent'); responseDiv.style.display = 'block'; contentDiv.textContent = 'AI思考中...'; try { await new Promise(resolve => setTimeout(resolve, 1000)); const answer = await getAIAnswer(question); contentDiv.textContent = answer; remaining--; usageHistory.push({ time: Date.now(), question }); localStorage.setItem('remaining', remaining); localStorage.setItem('usageHistory', JSON.stringify(usageHistory)); updateRemaining(); input.value = ''; } catch (e) { contentDiv.textContent = '抱歉，AI服务暂时不可用，请稍后重试。'; } }
async function getAIAnswer(question) { return `你问: "${question}" \n\n这是一个演示回复。接入真实AI后，这里会显示AI的回答。\n\n接入方案推荐:\n1. Cloudflare Workers AI (免费)\n2. Groq API (免费额度)\n3. 自己搭建的本地AI服务`; }
function updateRemaining() { document.getElementById('remaining').textContent = remaining; if (remaining <= 0) { document.getElementById('upgradeBanner').style.display = 'block'; } }
